In [94]:
import os

from sqlalchemy import and_, or_
import pandas as pd
pd.set_option("display.max_rows", None)

from grdb.config import Config
from grdb.database.v1_1_0 import dal as db1     # prod dal
from grdb.database import dal as db2            # test dal
from grdb.database.v1_1_0 import Base as Base1  # prod base
from grdb.database import Base as Base2         # test base

from grdb.database.v1_1_0.models import Sample,Recipe,Author

In [95]:
# Setup old schema (production db) as db1 using read only
config_prefix = "PROD_DATABASE"
config_suffix = "_READ"
conf = Config(prefix=config_prefix, suffix=config_suffix, debug=True, try_secrets=False)
db1.init_db(conf, privileges={"read": True, "write": False, "validate": False})
# Testing Configuration and dal initialization
config_prefix = "DEV_DATABASE"
config_suffix = "_ADMIN" 
conf = Config(prefix=config_prefix, suffix=config_suffix, debug=True, try_secrets=False)
db2.init_db(conf, privileges={"read": True, "write": True, "validate": True})

# 0) Stand up fresh empty db2
ses2 = db2.Session()
ses2.close()
Base2.metadata.drop_all(bind=db2.engine)
Base2.metadata.create_all(bind=db2.engine)

In [96]:
# Get all of the samples with their recipe data
ses1 = db1.Session()
pd.read_sql(
    ses1.query(Sample,Recipe).filter(Sample.id==Recipe.sample_id)
    .statement,
    ses1.bind,
)
# For each row:
# 1) Create Expirment row, use ll 1:1 mapped columns
# 1) Get author info from sample.recipe
# 2) create author row (if not exists)
# 3) Add author id to

,id,software_name,software_version,primary_sem_file_id,nanohub_userid,experiment_date,material_name,validated,id_1,sample_id,thickness,diameter,length,catalyst,tube_diameter,cross_sectional_area,tube_length,base_pressure,dewpoint,sample_surface_area
0,1,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,1,1,0.2,NaN,NaN,Palladium,55.0,2376.0,760.0,0.015500,None,50.0
1,2,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,2,2,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015400,None,1500.0
2,3,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,3,3,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015400,None,1500.0
3,4,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,4,4,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015400,None,1500.0
4,5,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,5,5,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015400,None,1500.0
5,6,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,6,6,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015400,None,1500.0
6,7,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,7,7,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015400,None,1500.0
7,8,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,8,8,0.3,NaN,NaN,Nickel,50.8,2026.8,762.0,0.015000,None,75.0
8,9,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,9,9,0.3,NaN,NaN,Nickel,50.8,2026.8,762.0,0.015000,None,75.0
9,10,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,10,10,0.3,NaN,NaN,Nickel,50.8,2026.8,762.0,0.015000,None,22.5
10,11,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,11,11,0.3,NaN,NaN,Nickel,50.8,2026.8,762.0,0.015000,None,75.0
11,12,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,12,12,0.3,NaN,NaN,Nickel,50.8,2026.8,762.0,0.015000,None,75.0
12,13,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,13,13,0.3,NaN,NaN,Nickel,50.8,2026.8,762.0,0.015000,None,75.0
13,14,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,14,14,NaN,NaN,NaN,Nickel,50.8,2026.8,762.0,0.015000,None,NaN
14,15,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,15,15,0.3,NaN,NaN,Nickel,50.8,2026.8,762.0,0.015000,None,75.0
15,16,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,16,16,0.3,NaN,NaN,Nickel,50.8,2026.8,762.0,0.015000,None,75.0
16,17,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,17,17,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.016000,None,1500.0
17,18,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,18,18,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.016000,None,1500.0
18,19,gresq,1.0.0-dev1,None,NaN,2017-09-26,Graphene,True,19,19,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015200,None,1500.0
19,20,gresq,1.0.0-dev1,None,NaN,2017-09-28,Graphene,True,20,20,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015300,None,1500.0
20,21,gresq,1.0.0-dev1,None,NaN,2017-10-10,Graphene,True,21,21,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015500,None,1500.0
21,22,gresq,1.0.0-dev1,None,NaN,2017-10-10,Graphene,True,22,22,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015300,None,1500.0
22,23,gresq,1.0.0-dev1,None,NaN,2018-03-14,Graphene,True,23,23,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.017800,None,1500.0
23,24,gresq,1.0.0-dev1,None,NaN,2018-03-14,Graphene,True,24,24,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.017800,None,1500.0
24,25,gresq,1.0.0-dev1,None,NaN,2018-03-14,Graphene,True,25,25,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.017800,None,1500.0
25,26,gresq,1.0.0-dev1,None,NaN,2018-03-14,Graphene,True,26,26,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.017800,None,1500.0
26,27,gresq,1.0.0-dev1,None,NaN,2018-03-21,Graphene,True,27,27,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.018200,None,1500.0
27,28,gresq,1.0.0-dev1,None,NaN,2018-04-12,Graphene,True,28,28,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.018200,None,1500.0
28,29,gresq,1.0.0-dev1,None,NaN,2018-04-13,Graphene,True,29,29,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019000,None,1500.0
29,30,gresq,1.0.0-dev1,None,NaN,2018-04-14,Graphene,True,30,30,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019000,None,1500.0
30,31,gresq,1.0.0-dev1,None,NaN,2018-04-15,Graphene,True,31,31,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019400,None,1500.0
31,32,gresq,1.0.0-dev1,None,NaN,2018-04-16,Graphene,True,32,32,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019200,None,1500.0
32,33,gresq,1.0.0-dev1,None,NaN,2018-04-16,Graphene,True,33,33,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019200,None,1500.0
33,34,gresq,1.0.0-dev1,None,NaN,2018-04-16,Graphene,True,34,34,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019200,None,1500.0
34,35,gresq,1.0.0-dev1,None,NaN,2018-04-17,Graphene,True,35,35,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019100,None,1500.0
35,36,gresq,1.0.0-dev1,None,NaN,2018-04-17,Graphene,True,36,36,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,NaN,None,1500.0
36,37,gresq,1.0.0-dev1,None,NaN,2018-04-17,Graphene,True,37,37,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,NaN,None,1500.0
37,38,gresq,1.0.0-dev1,None,NaN,2018-04-20,Graphene,True,38,38,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,NaN,None,1500.0
38,39,gresq,1.0.0-dev1,None,NaN,2018-04-20,Graphene,True,39,39,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019100,None,1500.0
39,40,gresq,1.0.0-dev1,None,NaN,2018-04-20,Graphene,True,40,40,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,NaN,None,1500.0
40,41,gresq,1.0.0-dev1,None,NaN,2018-04-22,Graphene,True,41,41,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,NaN,None,1500.0
41,42,gresq,1.0.0-dev1,None,NaN,2018-04-23,Graphene,True,42,42,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019100,None,1500.0
42,43,gresq,1.0.0-dev1,None,NaN,2018-04-23,Graphene,True,43,43,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019100,None,1500.0
43,44,gresq,1.0.0-dev1,None,NaN,2017-08-21,Graphene,True,44,44,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.016200,None,1500.0
44,45,gresq,1.0.0-dev1,None,NaN,2017-09-03,Graphene,True,45,45,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.016000,None,1500.0
45,46,gresq,1.0.0-dev1,None,NaN,2017-09-03,Graphene,True,46,46,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015600,None,1500.0
46,47,gresq,1.0.0-dev1,None,NaN,2017-09-04,Graphene,True,47,47,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015100,None,1500.0
47,48,gresq,1.0.0-dev1,None,NaN,2017-09-28,Graphene,True,48,48,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015400,None,1500.0
48,49,gresq,1.0.0-dev1,None,NaN,2017-09-28,Graphene,True,49,49,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015700,None,1500.0
49,50,gresq,1.0.0-dev1,None,NaN,2017-10-09,Graphene,True,50,50,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.014700,None,1500.0
50,51,gresq,1.0.0-dev1,None,NaN,2018-01-09,Graphene,True,51,51,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.015000,None,1500.0
51,52,gresq,1.0.0-dev1,None,NaN,2018-01-09,Graphene,True,52,52,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.014700,None,1500.0
52,53,gresq,1.0.0-dev1,None,NaN,2018-01-12,Graphene,True,53,53,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.014900,None,1500.0
53,54,gresq,1.0.0-dev1,None,NaN,2018-01-12,Graphene,True,54,54,0.2,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.014500,None,1500.0
54,55,gresq,1.0.0-dev1,None,NaN,2018-04-15,Graphene,True,55,55,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019200,None,1500.0
55,56,gresq,1.0.0-dev1,None,NaN,2018-05-30,Graphene,True,56,56,1.0,NaN,NaN,Palladium leaf,50.8,2026.8,762.0,0.019100,None,1500.0
56,57,gresq,0.0.0,None,265127.0,2012-07-12,Graphene,True,57,57,NaN,127.0,1000.0,Palladium,NaN,NaN,NaN,760.000000,None,NaN
57,58,gresq,0.0.0,None,265127.0,2012-07-12,Graphene,True,58,58,NaN,127.0,1000.0,Palladium,NaN,NaN,NaN,760.000000,None,NaN
58,59,gresq,0.0.0,None,265127.0,2012-07-12,Graphene,True,59,59,NaN,127.0,1000.0,Palladium,NaN,NaN,NaN,760.000000,None,NaN
59,60,gresq,0.0.0,None,265127.0,2012-07-12,Graphene,True,60,60,NaN,127.0,1000.0,Palladium,NaN,NaN,NaN,760.000000,None,NaN
60,61,gresq,0.0.0,None,265127.0,2014-06-10,Graphene,True,61,61,25.0,NaN,NaN,Palladium,25.4,507.0,NaN,0.007501,None,NaN
61,62,gresq,0.0.0,None,265127.0,2014-06-10,Graphene,True,62,62,25.0,NaN,NaN,Platinum,40.0,1257.0,NaN,760.000000,None,NaN
62,63,gresq,0.0.0,None,265127.0,2014-06-10,Graphene,True,63,63,25.0,NaN,NaN,Platinum,40.0,1257.0,NaN,760.000000,None,NaN
63,64,gresq,0.0.0,None,265127.0,2012-02-28,Graphene,True,64,64,200.0,NaN,NaN,Platinum,NaN,NaN,NaN,760.000000,None,NaN
64,65,gresq,0.0.0,None,265127.0,2015-07-15,Graphene,True,65,65,25.0,NaN,NaN,Platinum,28.0,616.0,NaN,760.000000,None,NaN
65,66,gresq,0.0.0,None,265127.0,2014-11-11,Graphene,True,66,66,350.0,NaN,NaN,Copper,102.0,8107.0,NaN,0.080000,None,NaN
66,67,gresq,0.0.0,None,265127.0,2014-11-11,Graphene,True,67,67,350.0,NaN,NaN,Copper,102.0,8107.0,NaN,0.080000,None,NaN
67,68,gresq,0.0.0,None,265127.0,2009-06-05,Graphene,True,68,68,25.0,NaN,NaN,Copper,22.0,380.0,NaN,0.500000,None,NaN
68,69,gresq,0.0.0,None,210937.0,2019-07-12,Graphene,True,69,69,25.0,5000.0,10000.0,Copper,25.4,506.0,1000.0,760.000000,None,1.0

In [97]:
ses1 = db1.Session()
unique_substrate_query = ses1.query(Recipe.catalyst, Recipe.thickness, Recipe.diameter, Recipe.length, Recipe.sample_surface_area).distinct().filter(
        or_(
            Recipe.catalyst != None,
            Recipe.thickness != None,
            Recipe.diameter != None,
            Recipe.sample_surface_area != None,
            Recipe.length != None,
        )
    )

pd.read_sql(
    unique_substrate_query.statement,
    ses1.bind,
)

          catalyst  thickness  diameter   length  sample_surface_area
0        Palladium        0.2       NaN      NaN                 50.0
1   Palladium leaf        0.2       NaN      NaN               1500.0
2           Nickel        0.3       NaN      NaN                 75.0
3           Nickel        0.3       NaN      NaN                 22.5
4           Nickel        NaN       NaN      NaN                  NaN
5   Palladium leaf        1.0       NaN      NaN               1500.0
6        Palladium        NaN     127.0   1000.0                  NaN
7        Palladium       25.0       NaN      NaN                  NaN
8         Platinum       25.0       NaN      NaN                  NaN
9         Platinum      200.0       NaN      NaN                  NaN
10          Copper      350.0       NaN      NaN                  NaN
11          Copper       25.0       NaN      NaN                  NaN
12          Copper       25.0    5000.0  10000.0                  1.0

In [98]:
# Test query for furnace data

ses1 = db1.Session()
unique_furnace_query = ses1.query(Recipe.tube_diameter, Recipe.cross_sectional_area, Recipe.tube_length).distinct().filter(
        or_(
            Recipe.tube_diameter != None,
            Recipe.cross_sectional_area != None,
            Recipe.tube_length != None,
        )
    )
pd.read_sql(
    unique_furnace_query.statement,
    ses1.bind,
)

   tube_diameter  cross_sectional_area  tube_length
0           55.0                2376.0        760.0
1           50.8                2026.8        762.0
2           25.4                 507.0          NaN
3           40.0                1257.0          NaN
4           28.0                 616.0          NaN
5          102.0                8107.0          NaN
6           22.0                 380.0          NaN
7           25.4                 506.0       1000.0

In [99]:
# Read all unique authors from old schema
from grdb.database.v1_1_0.models import Author

ses1 = db1.Session()
#unique_authors_query = ses1.query(
#        Author.sample_id,Author.first_name, Author.last_name, Author.institution
#    ).filter(Author.sample_id==Sample.id).group_by(Author.sample_id,Author.first_name, Author.last_name)
unique_authors_query = ses1.query(
        Author.first_name, Author.last_name, Author.institution
    ).distinct()
pd.read_sql(
    unique_authors_query.statement,
    ses1.bind,
)

    first_name         last_name                                 institution
0       Kaihao             Zhang  University of Illinois at Urbana-Champaign
1     Xiaohong                An                     Northeastern University
2       Fangze               Liu                     Northeastern University
3    Yung Joon              Jung                     Northeastern University
4      Swastik               Kar                     Northeastern University
5       Doglin                Ma                           Peking University
6       Mengxi               Liu                           Peking University
7         Teng               Gao                           Peking University
8         Cong                Li                           Peking University
9       Jingyu               Sun                           Peking University
10      Yufeng               Nie                           Peking University
11    Qingqing                Ji                           Peking University
12          Yu             Zhang                           Peking University
13       Xiuju              Song                           Peking University
14     Yanfeng             Zhang                           Peking University
15    Zhongfan               Liu                           Peking University
16          Ke              Xiao                         Tsinghua University
17    Huaqiang                Wu                         Tsinghua University
18    Hongming                Lv                         Tsinghua University
19    Xiaoming                Wu                         Tsinghua University
20          He              Qian                         Tsinghua University
21        Libo               Gao                 Chinese Academy of Sciences
22      Wencai               Ren                 Chinese Academy of Sciences
23     Huilong                Xu                           Peking University
24          Li               Jin                 Chinese Academy of Sciences
25    Zhenxing              Wang                           Peking University
26        Teng                Ma                 Chinese Academy of Sciences
27    Lai-Peng                Ma                 Chinese Academy of Sciences
28     Zhiyong             Zhang                           Peking University
29       Qiang                Fu                 Chinese Academy of Sciences
30    Lian-Mao              Peng                           Peking University
31       Xinhe               Bao                 Chinese Academy of Sciences
32    Hui-Ming             Cheng                 Chinese Academy of Sciences
33     Vitaliy           Babenko                        University of Oxford
34      Adrian           Murdock                        University of Oxford
35       Antal              Koos                        University of Oxford
36        Jude           Britton                        University of Oxford
37      Alison          Crossley                        University of Oxford
38      Philip           Holdway                        University of Oxford
39    Jonathan            Moffat          Oxford Instruments Asylum Research
40        Jian             Huang                        University of Oxford
41        Jack  Alexander-Webber                        University of Oxford
42       Robin          Nicholas                        University of Oxford
43      Nicole           Grobert                        University of Oxford
44    Dong Soo              Choi                     Sungkyunkwan University
45    Keun Soo               Kim                           Sejong University
46  Hyeongkeun               Kim      Korea Electronics Technology Institute
47        Yena               Kim                     Sungkyunkwan University
48    TaeYoung               Kim                           Gachon University
49     Se-hyun               Rhy      Korea Electronics Technology Institute
50   Cheol-Min              Yang   Korea Institute of Science and Technology
51      Dae Ho              Yoon                     Sungkyunkwan University
52    Woo Seok              Yang      Korea Electronics Technology Institute
53     Xuesong                Li               University of Texas at Austin
54      Weiwei               Cai               University of Texas at Austin
55       Jinho                An               University of Texas at Austin
56     Seyoung               Kim               University of Texas at Austin
57     Junghyo               Nah               University of Texas at Austin
58    Dongxing              Yang               University of Texas at Austin
59     Richard             Piner               University of Texas at Austin
60       Aruna       Velamakanni               University of Texas at Austin
61       Inhwa              Jung               University of Texas at Austin
62     Emanuel             Tutuc               University of Texas at Austin
63      Sanjay          Banerjee               University of Texas at Austin
64       Luigi           Colombo                           Texas Instruments
65      Rodney             Ruoff               University of Texas at Austin
66     Mitisha            Surana  University of Illinois at Urbana-Champaign

In [100]:
ses1 = db1.Session
authors = ses1.query(
    Author.sample_id, Author.first_name, Author.last_name, Author.institution
).group_by(Author.first_name, Author.last_name)
ses1.query(Sample.id,Sample.nanohub_userid).filter(Sample.id.in_(authors))

In [101]:
ses1 = db1.Session()
# authors = ses1.query(Author.first_name, Author.last_name, Author.institution).distinct()
# TODO: SAMPLE TABLE IS COMPLETELY EMPTY
samples = ses1.query(Sample,Recipe).filter(Sample.id==Recipe.sample_id)
for s in samples:
    print(f"name: {s.Sample.material_name}")
    print(f"{s.Recipe.base_pressure,s.Recipe.catalyst,s.Recipe.thickness,s.Recipe.diameter,s.Recipe.length,s.Recipe.sample_surface_area}")

name: Graphene
(0.0155, 'Palladium', 0.2, None, None, 50.0)
name: Graphene
(0.0154, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 22.5)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', None, None, None, None)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.016, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.016, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0152, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0153, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0155, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0153, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0178, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0178, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0178, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0178, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0182, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0182, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.019, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.019, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0194, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0192, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0192, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0192, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0162, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.016, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0156, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0151, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0157, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0147, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.015, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0147, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0149, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0145, 'Palladium leaf', 0.2, None, None, 1500.0)
name: Graphene
(0.0192, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium leaf', 1.0, None, None, 1500.0)
name: Graphene
(760.0, 'Palladium', None, 127.0, 1000.0, None)
name: Graphene
(760.0, 'Palladium', None, 127.0, 1000.0, None)
name: Graphene
(760.0, 'Palladium', None, 127.0, 1000.0, None)
name: Graphene
(760.0, 'Palladium', None, 127.0, 1000.0, None)
name: Graphene
(0.00750064, 'Palladium', 25.0, None, None, None)
name: Graphene
(760.0, 'Platinum', 25.0, None, None, None)
name: Graphene
(760.0, 'Platinum', 25.0, None, None, None)
name: Graphene
(760.0, 'Platinum', 200.0, None, None, None)
name: Graphene
(760.0, 'Platinum', 25.0, None, None, None)
name: Graphene
(0.08, 'Copper', 350.0, None, None, None)
name: Graphene
(0.08, 'Copper', 350.0, None, None, None)
name: Graphene
(0.5, 'Copper', 25.0, None, None, None)
name: Graphene
(760.0, 'Copper', 25.0, 5000.0, 10000.0, 1.0)

In [102]:
# This is a prototype to migrate sem file data
from grdb.database.v1_1_0.models import SemFile, SemAnalysis

ses1 = db1.Session()

sem_file_query = ses1.query(SemFile)
pd.read_sql(
    sem_file_query.statement,
    ses1.bind,
)

,id,sample_id,filename,url,default_analysis_id
0,1,19,KZPd_170926-2_SEM1.tif,https://app.box.com/shared/static/0gcoswatti4d...,None
1,2,19,KZPd_170926-2_SEM2.tif,https://app.box.com/shared/static/tqscru4t48dm...,None
2,3,20,KZPd_170928-3_SEM2.tif,https://app.box.com/shared/static/r4jcbampmdn3...,None
3,4,20,KZPd_170928-3_SEM1.tif,https://app.box.com/shared/static/wcfz6ikrzb46...,None
4,5,21,KZPd_171010-1_SEM1.tif,https://app.box.com/shared/static/8xalvtw1u9vo...,None
5,6,21,KZPd_171010-1_SEM2.tif,https://app.box.com/shared/static/zgu2e631r420...,None
6,7,22,KZPd_171010-2_SEM2.tif,https://app.box.com/shared/static/tp024cn0s7yt...,None
7,8,22,KZPd_171010-2_SEM1.tif,https://app.box.com/shared/static/quqzml0oah67...,None
8,9,23,KZPd_180314-1_SEM1.tif,https://app.box.com/shared/static/5vzum9ze0dqo...,None
9,10,23,KZPd_180314-1_SEM2.tif,https://app.box.com/shared/static/ap53ichjfi1s...,None
10,11,23,KZPd_180314-1_SEM3.tif,https://app.box.com/shared/static/9qru6tqkyhh4...,None
11,12,24,KZPd_180314-2_SEM2.tif,https://app.box.com/shared/static/e0pifltwhhzl...,None
12,13,24,KZPd_180314-2_SEM3.tif,https://app.box.com/shared/static/sjrk4kzvbtm0...,None
13,14,24,KZPd_180314-2_SEM1.tif,https://app.box.com/shared/static/2924fiqhk0kl...,None
14,15,25,KZPd_180314-3_SEM1.tif,https://app.box.com/shared/static/k2qrcg7q82wr...,None
15,16,26,KZPd_180314-4_SEM2.tif,https://app.box.com/shared/static/efhs8ubl8fgt...,None
16,17,26,KZPd_180314-4_SEM3.tif,https://app.box.com/shared/static/p4vx4402efuq...,None
17,18,26,KZPd_180314-4_SEM1.tif,https://app.box.com/shared/static/l0fzjp8jt1zd...,None
18,19,27,KZPd_180321-1_SEM3(Thresh).tif,https://app.box.com/shared/static/in9joxgegk7k...,None
19,20,27,KZPd_180321-1_SEM1.tif,https://app.box.com/shared/static/4v4em4r9jd4g...,None
20,21,27,KZPd_180321-1_SEM3.tif,https://app.box.com/shared/static/6gboy7hzvh5k...,None
21,22,27,KZPd_180321-1_SEM2.tif,https://app.box.com/shared/static/c7c2cdxhbmaa...,None
22,23,27,KZPd_180321-1_SEM1(Thresh).tif,https://app.box.com/shared/static/2o50w1prk1rt...,None
23,24,27,KZPd_180321-1_SEM2(Thresh).tif,https://app.box.com/shared/static/a3s62pwecxjy...,None
24,25,28,KZPd_180412-1_SEM1(Thresh).tif,https://app.box.com/shared/static/3ly4q1xtt1eo...,None
25,26,28,KZPd_180412-1_SEM2(Thresh).tif,https://app.box.com/shared/static/6n9eit97429v...,None
26,27,28,KZPd_180412-1_SEM3(Thresh).tif,https://app.box.com/shared/static/xdgqhecdrxp3...,None
27,28,28,KZPd_180412-1_SEM3.tif,https://app.box.com/shared/static/v2x18qo2jp00...,None
28,29,28,KZPd_180412-1_SEM2.tif,https://app.box.com/shared/static/ooqpopdvg7x3...,None
29,30,28,KZPd_180412-1_SEM1.tif,https://app.box.com/shared/static/cvqw94uka660...,None
30,31,29,KZPd_180413-1_SEM3(Thresh).tif,https://app.box.com/shared/static/u5h64ae35udy...,None
31,32,29,KZPd_180413-1_SEM3.tif,https://app.box.com/shared/static/lzu094sa29ec...,None
32,33,29,KZPd_180413-1_SEM2.tif,https://app.box.com/shared/static/1f7e6t0rmy6x...,None
33,34,29,KZPd_180413-1_SEM1.tif,https://app.box.com/shared/static/ne2ya7ju8qvq...,None
34,35,29,KZPd_180413-1_SEM2(Thresh).tif,https://app.box.com/shared/static/l5ugpw6hmfep...,None
35,36,29,KZPd_180413-1_SEM1(Thresh).tif,https://app.box.com/shared/static/p0qg04vthy6r...,None
36,37,30,KZPd_180414-1_SEM1.tif,https://app.box.com/shared/static/prn5yks40glk...,None
37,38,30,KZPd_180414-1_SEM2.tif,https://app.box.com/shared/static/2x6ppozxoewv...,None
38,39,31,KZPd_180415-1_SEM1.tif,https://app.box.com/shared/static/6zjl51q9dakz...,None
39,40,31,KZPd_180415-1_SEM2.tif,https://app.box.com/shared/static/s6ltin4z100h...,None
40,41,31,KZPd_180415-1_SEM1(Thresh).tif,https://app.box.com/shared/static/s3ugpma6ukho...,None
41,42,31,KZPd_180415-1_SEM2(Thresh).tif,https://app.box.com/shared/static/1edip2wpgy50...,None
42,43,32,KZPd_180416-1_SEM3(Thresh).tif,https://app.box.com/shared/static/miowy3jgyy12...,None
43,44,32,KZPd_180416-1_SEM1.tif,https://app.box.com/shared/static/ikuayfbj3ztx...,None
44,45,32,KZPd_180416-1_SEM3.tif,https://app.box.com/shared/static/83e1v46dpat7...,None
45,46,32,KZPd_180416-1_SEM2.tif,https://app.box.com/shared/static/djtobkbarfoh...,None
46,47,32,KZPd_180416-1_SEM1(Thresh).tif,https://app.box.com/shared/static/aebaenkckk04...,None
47,48,32,KZPd_180416-1_SEM2(Thresh).tif,https://app.box.com/shared/static/jd6td12zicyb...,None
48,49,33,KZPd_180416-2_SEM2(Thresh).tif,https://app.box.com/shared/static/g89w3jg376ev...,None
49,50,33,KZPd_180416-2_SEM1(Thresh).tif,https://app.box.com/shared/static/h6bfun46mp1z...,None
50,51,33,KZPd_180416-2_SEM3(Thresh).tif,https://app.box.com/shared/static/jxzq8y8rt54n...,None
51,52,33,KZPd_180416-2_SEM3.tif,https://app.box.com/shared/static/qkkc7l5vnf1j...,None
52,53,33,KZPd_180416-2_SEM2.tif,https://app.box.com/shared/static/iut439f68cz7...,None
53,54,33,KZPd_180416-2_SEM1.tif,https://app.box.com/shared/static/stt7dey19b38...,None
54,55,34,KZPd_180416-3_SEM1(Thresh).tif,https://app.box.com/shared/static/z4prvrhh33f1...,None
55,56,34,KZPd_180416-3_SEM2(Thresh).tif,https://app.box.com/shared/static/3vsxs20wde4w...,None
56,57,34,KZPd_180416-3_SEM2.tif,https://app.box.com/shared/static/oj27fmh07seb...,None
57,58,34,KZPd_180416-3_SEM1.tif,https://app.box.com/shared/static/8oyxxaxllu16...,None
58,59,35,KZPd_180417-1_SEM1.tif,https://app.box.com/shared/static/3bg2ahalbsbd...,None
59,60,35,KZPd_180417-1_SEM2.tif,https://app.box.com/shared/static/17ca0n77e7pz...,None
60,61,36,KZPd_180417-2_SEM3.tif,https://app.box.com/shared/static/tz366i6vp6uw...,None
61,62,36,KZPd_180417-2_SEM2.tif,https://app.box.com/shared/static/9pzrmhckckbf...,None
62,63,36,KZPd_180417-2_SEM1.tif,https://app.box.com/shared/static/y3wqcdof7kfy...,None
63,64,37,KZPd_180417-3_SEM3.tif,https://app.box.com/shared/static/hx4w2u5yqmgo...,None
64,65,37,KZPd_180417-3_SEM2.tif,https://app.box.com/shared/static/k1ph2r7l065o...,None
65,66,37,KZPd_180417-3_SEM1.tif,https://app.box.com/shared/static/04txg6zn2ug3...,None
66,67,38,KZPd_180420-1_SEM1.tif,https://app.box.com/shared/static/jvcfy81w7vbe...,None
67,68,38,KZPd_180420-1_SEM3.tif,https://app.box.com/shared/static/smgttrm84x4n...,None
68,69,38,KZPd_180420-1_SEM2.tif,https://app.box.com/shared/static/cfrm9w2y88fv...,None
69,70,39,KZPd_180420-2_SEM3.tif,https://app.box.com/shared/static/ggb1bfc2ne2e...,None
70,71,39,KZPd_180420-2_SEM2.tif,https://app.box.com/shared/static/5yvbabw5dfgo...,None
71,72,39,KZPd_180420-2_SEM1.tif,https://app.box.com/shared/static/9ae057vvlgg3...,None
72,73,40,KZPd_180420-3_SEM3.tif,https://app.box.com/shared/static/qnzgvet8g2j2...,None
73,74,40,KZPd_180420-3_SEM2.tif,https://app.box.com/shared/static/ivcadgz2q007...,None
74,75,40,KZPd_180420-3_SEM1.tif,https://app.box.com/shared/static/vralcmc174yn...,None
75,76,41,KZPd_180422-2_SEM2.tif,https://app.box.com/shared/static/bj2zzmc6fq7v...,None
76,77,41,KZPd_180422-2_SEM3.tif,https://app.box.com/shared/static/0dn5qhp76d6y...,None
77,78,41,KZPd_180422-2_SEM1.tif,https://app.box.com/shared/static/ona1fm3su2f3...,None
78,79,42,KZPd_180423-1_SEM1.tif,https://app.box.com/shared/static/lyjmd87du8j0...,None
79,80,42,KZPd_180423-1_SEM2.tif,https://app.box.com/shared/static/0z5rsmnz4c6m...,None
80,81,43,20180423-2_Pd heavy leaf_01_e.tif,https://app.box.com/shared/static/75ncesy916sj...,None
81,82,43,20180423-2_Pd heavy leaf_00_e.tif,https://app.box.com/shared/static/uwsodzl7yhnm...,None
82,83,55,KZPd_180415-2_SEM2.tif,https://app.box.com/shared/static/o4ixdmkpteif...,None
83,84,55,KZPd_180415-2_SEM2(Thresh).tif,https://app.box.com/shared/static/88vwpqrum6cm...,None
84,85,55,KZPd_180415-2_SEM1.tif,https://app.box.com/shared/static/lxy5vnc8y5sa...,None
85,86,55,KZPd_180415-2_SEM1(Thresh).tif,https://app.box.com/shared/static/1zmztsqo9nzd...,None
86,87,69,20190712_2_Cu_3CH4_300H2_1000C_30mins_5_e.tif,https://app.box.com/shared/static/tknlp96atbur...,None

In [103]:
# This is a prototype to migrate raman file data
from grdb.database.v1_1_0.models import RamanFile, RamanSet, RamanSpectrum

ses1 = db1.Session()

raman_file_query = ses1.query(RamanFile)
pd.read_sql(
    raman_file_query.statement,
    ses1.bind,
)

,id,sample_id,filename,url,wavelength
0,1,19,KZPd_170926-2_Raman1.txt,https://app.box.com/shared/static/dntoyp6st99k...,532.0
1,2,20,KZPd_170928-2_Raman1.txt,https://app.box.com/shared/static/1i0k14kcgxna...,532.0
2,3,21,KZPd_171010-1_Raman1.txt,https://app.box.com/shared/static/kxqxjevcyhgl...,532.0
3,4,22,KZPd_171010-2_Raman1.txt,https://app.box.com/shared/static/vi52dz5iuvle...,532.0
4,5,27,20180321-1_sample.txt,https://app.box.com/shared/static/wkyyc6if2xq3...,532.0
5,6,32,sample.txt,https://app.box.com/shared/static/n5edqfjw59r9...,532.0
6,7,33,SAMPLE.txt,https://app.box.com/shared/static/av8rs1776813...,532.0
7,8,34,sample.txt,https://app.box.com/shared/static/b8h1g889lspt...,532.0
8,9,35,sample.txt,https://app.box.com/shared/static/mmrrr6r8tq9c...,532.0
9,10,39,sample.txt,https://app.box.com/shared/static/24hz65xtmyxa...,532.0
10,11,42,sample.txt,https://app.box.com/shared/static/jay77xvhhl9u...,532.0
11,12,43,sample.txt,https://app.box.com/shared/static/80wzaa8fjlud...,532.0
12,13,44,Sample spectrum.txt,https://app.box.com/shared/static/2dxdn7flm55p...,532.0
13,14,44,Sample spectrum KZPd_170821-2.txt,https://app.box.com/shared/static/jr8angeaysbf...,532.0
14,15,45,20170924_Gr on SiO2_2_spec.txt,https://app.box.com/shared/static/o1srfurup1sv...,532.0
15,16,46,20170924_Gr on SiO2_2_spec.txt,https://app.box.com/shared/static/nemjogie82np...,532.0
16,17,47,20170924_Gr on SiO2_2_spec.txt,https://app.box.com/shared/static/dzpb8pslfzq1...,532.0
17,18,48,20170926-4 on SiO2_1.txt,https://app.box.com/shared/static/w3e4e7nywjw6...,532.0
18,19,49,20170926-5 on SiO2_21.txt,https://app.box.com/shared/static/qvfj8e410jh1...,532.0
19,20,50,20171009-4 on SiO2_26.txt,https://app.box.com/shared/static/khvsd0vh3cp3...,532.0
20,21,51,Sample_20180109-1.txt,https://app.box.com/shared/static/9z8eblx64ij7...,532.0
21,22,52,Sample_20180109-2_2.txt,https://app.box.com/shared/static/wwjfvvffyvem...,532.0
22,23,53,Sample_20180112-1_1.txt,https://app.box.com/shared/static/l890g41s6qrx...,532.0
23,24,54,Sample_20180112-3_1.txt,https://app.box.com/shared/static/nz5uxw0opm7l...,532.0
24,25,55,sample.txt,https://app.box.com/shared/static/nub2ghe64qp0...,532.0
25,26,56,sample.txt,https://app.box.com/shared/static/v0nf0fnhfnr9...,532.0

In [104]:
raman_set_query = ses1.query(RamanSet)
pd.read_sql(
    raman_set_query.statement,
    ses1.bind,
)

,id,nanohub_userid,map_file,sample_id,experiment_date,d_to_g,gp_to_g,d_peak_shift,d_peak_amplitude,d_fwhm,g_peak_shift,g_peak_amplitude,g_fwhm,g_prime_peak_shift,g_prime_peak_amplitude,g_prime_fwhm
0,1,None,False,1,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,None,False,2,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,None,False,3,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,None,False,4,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,None,False,5,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,None,False,6,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,None,False,7,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,None,False,8,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,None,False,9,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,None,False,10,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,None,False,11,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,None,False,12,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,None,False,13,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,None,False,14,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,None,False,15,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,None,False,16,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,None,False,17,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,None,False,18,2019-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,None,False,19,2017-09-26,0.368784,2.642400,1351.42,0.145354,32.3961,1597.10,0.394144,33.0001,2688.41,1.041490,32.4792
19,20,None,False,20,2017-09-28,0.094736,0.577741,1356.97,0.097957,50.0000,1586.84,1.034000,33.0000,2702.44,0.597385,60.0000
20,21,None,False,21,2017-10-10,0.723474,3.359450,1347.80,0.217042,50.0000,1587.78,0.300000,60.0000,2683.78,1.007830,35.4183
21,22,None,False,22,2017-10-10,0.685830,2.683580,1343.95,0.255433,50.0000,1585.43,0.372445,60.0000,2673.10,0.999487,41.1548
22,23,None,False,23,2018-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,None,False,24,2018-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,None,False,25,2018-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,None,False,26,2018-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,None,False,27,2018-03-21,0.509089,3.418590,1332.40,0.152727,50.0000,1582.85,0.300000,49.0430,2674.65,1.025580,32.0000
27,28,None,False,28,2018-04-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,None,False,29,2018-04-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,None,False,30,2018-04-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,None,False,31,2018-04-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,None,False,32,2018-04-16,0.349931,2.017150,1300.00,0.177400,50.0000,1589.87,0.506958,33.0000,2677.79,1.022610,32.0000
32,33,None,False,33,2018-04-16,0.391546,2.538590,1345.31,0.159572,50.0000,1590.29,0.407543,33.0000,2685.99,1.034590,33.9584
33,34,None,False,34,2018-04-16,0.639385,3.227400,1335.09,0.196651,50.0000,1586.87,0.307563,60.0000,2681.00,0.992628,32.0000
34,35,None,False,35,2018-04-17,0.603363,3.438810,1343.28,0.181009,50.0000,1586.22,0.300000,58.6357,2682.10,1.031640,32.0000
35,36,None,False,36,2018-04-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37,None,False,37,2018-04-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38,None,False,38,2018-04-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,None,False,39,2018-04-20,0.159292,2.727220,1344.36,0.047787,50.0000,1580.13,0.300000,33.0000,2686.04,0.818165,32.0000
39,40,None,False,40,2018-04-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,None,False,41,2018-04-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,None,False,42,2018-04-23,0.478548,3.374090,1341.45,0.143564,50.0000,1580.75,0.300000,45.3229,2674.39,1.012230,32.0000
42,43,None,False,43,2018-04-23,0.149972,2.863010,1340.52,0.044992,50.0000,1574.81,0.300000,33.0000,2679.44,0.858902,32.0000
43,44,None,False,44,2017-08-21,0.066726,3.184860,1352.25,0.020018,50.0000,1582.40,0.300000,33.0000,2676.11,0.955457,32.0000
44,45,None,False,45,2017-09-03,1.069450,0.740229,1354.21,1.000000,50.0000,1598.23,0.935062,60.0000,2696.17,0.692160,49.4120
45,46,None,False,46,2017-09-03,0.165502,0.463538,1367.11,0.161792,50.0000,1593.80,0.977582,33.0000,2696.54,0.453147,45.0087
46,47,None,False,47,2017-09-04,0.725251,0.948552,1354.52,0.580256,50.0000,1593.69,0.800076,60.0000,2694.92,0.758914,49.9120
47,48,None,False,48,2017-09-28,0.231268,0.424475,1349.82,0.224987,50.0000,1586.59,0.972837,33.0000,2693.09,0.412945,59.4913
48,49,None,False,49,2017-09-28,3.215980,1.816160,1346.83,0.999338,28.1364,1594.67,0.310742,60.0000,2684.04,0.564358,42.9269
49,50,None,False,50,2017-10-09,0.428706,2.326840,1338.81,0.183526,50.0000,1594.77,0.428092,33.0000,2687.18,0.996099,32.0000
50,51,None,False,51,2018-01-09,0.187171,3.064520,1347.30,0.064212,50.0000,1582.24,0.343064,33.0000,2694.83,1.051330,33.1515
51,52,None,False,52,2018-01-09,0.217127,2.138360,1348.68,0.103878,50.0000,1584.07,0.478420,33.0000,2685.08,1.023030,34.3985
52,53,None,False,53,2018-01-12,0.186914,3.193870,1345.88,0.056074,50.0000,1582.69,0.300000,33.0000,2682.75,0.958162,32.0000
53,54,None,False,54,2018-01-12,0.216012,3.124650,1342.91,0.070874,50.0000,1583.48,0.328102,33.0000,2676.20,1.025200,32.3444
54,55,None,False,55,2018-04-15,0.407784,3.012440,1339.48,0.139249,50.0000,1584.91,0.341478,34.6196,2679.56,1.028680,32.0000
55,56,None,False,56,2018-05-30,0.795715,0.651089,1350.60,0.639978,50.0000,1585.76,0.804281,60.0000,2698.01,0.523659,60.0000
56,57,None,False,57,2019-11-12,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
57,58,None,False,58,2012-07-12,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
58,59,None,False,59,2012-07-12,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
59,60,None,False,60,2012-07-12,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
60,61,None,False,61,2014-06-10,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
61,62,None,False,62,2014-06-10,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
62,63,None,False,63,2014-06-10,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
63,64,None,False,64,2012-02-28,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
64,65,None,False,65,2015-07-15,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
65,66,None,False,66,2014-11-11,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
66,67,None,False,67,2014-11-11,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
67,68,None,False,68,2009-06-05,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000
68,69,None,False,69,2019-07-12,0.000000,0.000000,0.00,0.000000,0.0000,0.00,0.000000,0.0000,0.00,0.000000,0.0000

In [105]:
raman_spectrum_query = ses1.query(RamanSpectrum)
pd.read_sql(
    raman_spectrum_query.statement,
    ses1.bind,
)

,id,set_id,raman_file_id,software_name,software_version,xcoord,ycoord,percent,d_peak_shift,d_peak_amplitude,d_fwhm,g_peak_shift,g_peak_amplitude,g_fwhm,g_prime_peak_shift,g_prime_peak_amplitude,g_prime_fwhm
0,1,19,1,gsaraman,1.3.0-dev0,None,None,100.0,1351.42,0.145354,32.3961,1597.10,0.394144,33.0001,2688.41,1.041490,32.4792
1,2,20,2,gsaraman,1.3.0-dev0,None,None,100.0,1356.97,0.097957,50.0000,1586.84,1.034000,33.0000,2702.44,0.597385,60.0000
2,3,21,3,gsaraman,1.3.0-dev0,None,None,100.0,1347.80,0.217042,50.0000,1587.78,0.300000,60.0000,2683.78,1.007830,35.4183
3,4,22,4,gsaraman,1.3.0-dev0,None,None,100.0,1343.95,0.255433,50.0000,1585.43,0.372445,60.0000,2673.10,0.999487,41.1548
4,5,27,5,gsaraman,1.3.0-dev0,None,None,100.0,1332.40,0.152727,50.0000,1582.85,0.300000,49.0430,2674.65,1.025580,32.0000
5,6,32,6,gsaraman,1.3.0-dev0,None,None,100.0,1300.00,0.177400,50.0000,1589.87,0.506958,33.0000,2677.79,1.022610,32.0000
6,7,33,7,gsaraman,1.3.0-dev0,None,None,100.0,1345.31,0.159572,50.0000,1590.29,0.407543,33.0000,2685.99,1.034590,33.9584
7,8,34,8,gsaraman,1.3.0-dev0,None,None,100.0,1335.09,0.196651,50.0000,1586.87,0.307563,60.0000,2681.00,0.992628,32.0000
8,9,35,9,gsaraman,1.3.0-dev0,None,None,100.0,1343.28,0.181009,50.0000,1586.22,0.300000,58.6357,2682.10,1.031640,32.0000
9,10,39,10,gsaraman,1.3.0-dev0,None,None,100.0,1344.36,0.047787,50.0000,1580.13,0.300000,33.0000,2686.04,0.818165,32.0000
10,11,42,11,gsaraman,1.3.0-dev0,None,None,100.0,1341.45,0.143564,50.0000,1580.75,0.300000,45.3229,2674.39,1.012230,32.0000
11,12,43,12,gsaraman,1.3.0-dev0,None,None,100.0,1340.52,0.044992,50.0000,1574.81,0.300000,33.0000,2679.44,0.858902,32.0000
12,13,44,13,gsaraman,1.3.0-dev0,None,None,50.0,1352.25,0.020018,50.0000,1582.40,0.300000,33.0000,2676.11,0.955457,32.0000
13,14,44,14,gsaraman,1.3.0-dev0,None,None,50.0,1352.25,0.020018,50.0000,1582.40,0.300000,33.0000,2676.11,0.955457,32.0000
14,15,45,15,gsaraman,1.3.0-dev0,None,None,100.0,1354.21,1.000000,50.0000,1598.23,0.935062,60.0000,2696.17,0.692160,49.4120
15,16,46,16,gsaraman,1.3.0-dev0,None,None,100.0,1367.11,0.161792,50.0000,1593.80,0.977582,33.0000,2696.54,0.453147,45.0087
16,17,47,17,gsaraman,1.3.0-dev0,None,None,100.0,1354.52,0.580256,50.0000,1593.69,0.800076,60.0000,2694.92,0.758914,49.9120
17,18,48,18,gsaraman,1.3.0-dev0,None,None,100.0,1349.82,0.224987,50.0000,1586.59,0.972837,33.0000,2693.09,0.412945,59.4913
18,19,49,19,gsaraman,1.3.0-dev0,None,None,100.0,1346.83,0.999338,28.1364,1594.67,0.310742,60.0000,2684.04,0.564358,42.9269
19,20,50,20,gsaraman,1.3.0-dev0,None,None,100.0,1338.81,0.183526,50.0000,1594.77,0.428092,33.0000,2687.18,0.996099,32.0000
20,21,51,21,gsaraman,1.3.0-dev0,None,None,100.0,1347.30,0.064212,50.0000,1582.24,0.343064,33.0000,2694.83,1.051330,33.1515
21,22,52,22,gsaraman,1.3.0-dev0,None,None,100.0,1348.68,0.103878,50.0000,1584.07,0.478420,33.0000,2685.08,1.023030,34.3985
22,23,53,23,gsaraman,1.3.0-dev0,None,None,100.0,1345.88,0.056074,50.0000,1582.69,0.300000,33.0000,2682.75,0.958162,32.0000
23,24,54,24,gsaraman,1.3.0-dev0,None,None,100.0,1342.91,0.070874,50.0000,1583.48,0.328102,33.0000,2676.20,1.025200,32.3444
24,25,55,25,gsaraman,1.3.0-dev0,None,None,100.0,1339.48,0.139249,50.0000,1584.91,0.341478,34.6196,2679.56,1.028680,32.0000
25,26,56,26,gsaraman,1.3.0-dev0,None,None,100.0,1350.60,0.639978,50.0000,1585.76,0.804281,60.0000,2698.01,0.523659,60.0000

In [106]:
unique_raman_spectrum_query = ses1.query(
        RamanSpectrum.xcoord, RamanSpectrum.ycoord
    ).distinct()
pd.read_sql(
    unique_raman_spectrum_query.statement,
    ses1.bind,
)

  xcoord ycoord
0   None   None

In [108]:
######################################################################################
# Migration script
# ToDo:
# - TESTING!!!
# - nanohub_userid
# - environment_conditions
# - sem_files + analysis
# - raman_files + analysis
# - software versions
######################################################################################

from grdb.database.v1_1_0.models import Author
from grdb.database.v1_1_0.models import SemFile
from grdb.database.v1_1_0.models import RamanFile
from grdb.database.v1_1_0.models import RamanSet
from grdb.database.v1_1_0.models import RamanSpectrum
from grdb.database.models import Author as Author2
from grdb.database.models import Furnace as Furnace2
from grdb.database.models import Experiment as Experiment2
from grdb.database.models import Recipe as Recipe2
from grdb.database.models import PreparationStep as PreparationStep2
from grdb.database.models import Substrate as Substrate2
from grdb.database.models import EnvironmentConditions as EnvironmentConditions2
from grdb.database.models import SemFile as SemFile2
from grdb.database.models import RamanFile as RamanFile2
from grdb.database.models import RamanAnalysis as RamanAnalysis2



commit = True
limit = 200

from math import isclose

# 0) Stand up fresh empty db2
print("Clearing destination database...")
ses2 = db2.Session()
ses2.close()
Base2.metadata.drop_all(bind=db2.engine)
Base2.metadata.create_all(bind=db2.engine)
print("done.")




print("Adding furnace rows...")
furnaces = unique_furnace_query
new_furnaces = [
    Furnace2(
        tube_diameter =  f.tube_diameter,
        cross_sectional_area = f.cross_sectional_area,
        tube_length = f.tube_length
    ) for f in furnaces
]
if commit:
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_furnaces)
print("done.")
       

print("Adding substrate rows...")
substrates = unique_substrate_query
new_substrates = [
    Substrate2(
        catalyst = s.catalyst,
        thickness = s.thickness,
        diameter = s.diameter,
        surface_area = s.sample_surface_area,
        length = s.length
    ) for s in substrates
]
if commit:
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_substrates)
print("done.")

print("Adding author rows...")
authors = unique_authors_query
new_authors = [
    Author2(
        first_name = a.first_name,
        last_name = a.last_name,
        institution = a.institution
    ) for a in authors
]

# Submit type of call/ insert/update
if commit:
    # call factory function gives live session from class 
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_authors)
print("done.")

print("Getting old sample data...")
ses1 = db1.Session()
samples = ses1.query(Sample,Recipe).filter(Sample.id==Recipe.sample_id).limit(limit)
oauthors = ses1.query(Author).all()
print("done.")

#####################################################################################
# At this point unique rows for furnace, substrate and Authors have been created
# Now, Loop back through the samples and match rows in furnace, substrate and authors
# Build a map from Experiment id  -> furnace_id, etc. for each sample/experiment id
# Note this assumes that the experiment id will map to the (old) sample id.
# ToDo
# - Add fields to preparation_step
# - Add sem_files
# - Add raman_files
# - Add properties
######################################################################################
ses3 = db2.Session()
new_furnaces = ses3.query(Furnace2).all()
new_substrates = ses3.query(Substrate2).all()
new_authors = ses3.query(Author2).all()
    
furnacemap = {}
substratemap = {}
authormap = {}
tol = 0.01
print ("Matching parent tables...")
for s in samples:
    authormap[s.Sample.id]=[]
    print(f"name: {s.Sample.material_name}")
    #print(f"{s.Recipe.base_pressure,s.Recipe.catalyst}")
    
    #################################################################################
    # Match to a row in the furnace table
    #################################################################################
    for f in new_furnaces:
        #print(f"id: {f.id}")
        match = match1 = match2 = match3 = False
        null = null1 = null2 = null3 = False
        if f.tube_diameter:
            if s.Sample.recipe.tube_diameter:
                if isclose(f.tube_diameter,s.Sample.recipe.tube_diameter,rel_tol=0.001,abs_tol=0.001):
                    match1 = True
        else:
            if not s.Sample.recipe.tube_diameter:
                match1 = True
                null1 = True
        if f.tube_length:
            if s.Sample.recipe.tube_length:
                if isclose(f.tube_length,s.Sample.recipe.tube_length,rel_tol=0.001,abs_tol=0.001):
                    match2 = True
        else:
            if not s.Sample.recipe.tube_length:
                match2 = True
                null2 = True
        if f.cross_sectional_area:
            if s.Sample.recipe.cross_sectional_area:
                if isclose(f.cross_sectional_area,s.Sample.recipe.cross_sectional_area,rel_tol=0.001,abs_tol=0.001):
                    match3 = True
        else:
            if not s.Sample.recipe.cross_sectional_area:
                match3 = True
                null3 = True
        # If there are any non null matches    
        match = match1 and match2 and match3
        if match:
            furnacemap[s.Sample.id] = f.id
            #print(f"match: {s.Sample.id}: {f.id}")
            break
        else:
            furnacemap[s.Sample.id] = None
            
        
    #################################################################################
    # Match to row in Substrate table
    #################################################################################
    for sb in new_substrates:
        match = match1 = match2 = match3 = match4 = match5 = False
        if sb.catalyst:
            if sb.catalyst == s.Sample.recipe.catalyst:
                match1 = True
        else:
            if not s.Sample.recipe.catalyst:
                match1 = True
        if sb.thickness:
            if s.Sample.recipe.thickness:
                if isclose(sb.thickness,s.Sample.recipe.thickness,rel_tol=tol,abs_tol=tol):
                    match2 = True
        else:
            if not s.Sample.recipe.thickness:
                match2 = True
        if sb.diameter:
            if s.Sample.recipe.diameter:
                if isclose(sb.diameter,s.Sample.recipe.diameter,rel_tol=tol,abs_tol=tol):
                    match3 = True
        else:
            if not s.Sample.recipe.diameter:
                match3 = True
        if sb.length:
            if s.Sample.recipe.length:
                if isclose(sb.length,s.Sample.recipe.length,rel_tol=tol,abs_tol=tol):
                    match4 = True
        else:
            if not s.Sample.recipe.length:
                match4 = True
        if sb.surface_area:
            if s.Sample.recipe.sample_surface_area:
                if isclose(sb.surface_area,s.Sample.recipe.sample_surface_area,rel_tol=tol,abs_tol=tol):
                    match5 = True
        else:
            if not s.Sample.recipe.sample_surface_area:
                match5 = True
        match = match1 and match2 and match3 and match4 and match5
        if match:
            substratemap[s.Sample.id] = sb.id
            break
        else:
            substratemap[s.Sample.id] = None
    #################################################################################
    # Match to row(s) in Author table
    #################################################################################
    for oa in oauthors:
        if not oa.sample_id == s.Sample.id:
            continue
        for na in new_authors:
            match = match1 = match2 = False
            if oa.first_name == na.first_name:
                match1 = True
            if oa.last_name == na.last_name:
                match2 = True
            match = match1 and match2
            if match:
                authormap[s.Sample.id].append(na)
                break
        
        
    

#Print out the maps
print (f"fmap: {furnacemap}")
print (f"sbmap: {substratemap}")
print(f"amap: {authormap}")
print ("Done.")        

#####################################################################################
#####################################################################################

print("Adding Experiment rows...")
with db2.session_scope(autocommit=True) as ses2:
    for s in samples:
        print(f"{s.Sample.id}")
        try:
            carbon_source = s.Recipe.carbon_source
        except IndexError:
            carbon_source = None
        

            
        # Add the new experiment based on the old sample
        # Create a recipe for each old sample and add all of its prep steps
        newexp = Experiment2(
                id=s.Sample.id,
                furnace_id = furnacemap[s.Sample.id],
                substrate_id = substratemap[s.Sample.id],
                authors = authormap[s.Sample.id],
                material_name=s.Sample.material_name,
                experiment_date=s.Sample.experiment_date,
                recipe = Recipe2(
                    carbon_source=carbon_source,
                    base_pressure=s.Recipe.base_pressure,
                    preparation_steps = [
                        PreparationStep2(
                            name=step.name,
                            step=step.step,
                            duration=step.duration,
                            furnace_pressure=step.furnace_pressure,
                            furnace_temperature=step.furnace_temperature,
                            sample_location=step.sample_location,
                            helium_flow_rate=step.helium_flow_rate,
                            hydrogen_flow_rate=step.hydrogen_flow_rate,
                            carbon_source_flow_rate=step.carbon_source_flow_rate,
                            argon_flow_rate=step.argon_flow_rate,
                            cooling_rate=step.cooling_rate
                        ) for step in s.Recipe.preparation_steps
                    ]
                    ),
                
                )
        
        ses2.add(newexp)

print("done.")

#####################################################################################
#####################################################################################

print("Adding Environment Conditions rows...")
new_environment_conditions = [
    EnvironmentConditions2(
        # TODO: Where do we get ambient temperature
        dew_point = s.Sample.recipe.dewpoint,
        ambient_temperature = 10
    ) for s in samples
]
for s in samples:
    print(f"{s.Sample.recipe.dewpoint}")
    print(f"{s.Sample.id}")
print(new_environment_conditions)
if commit:
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_environment_conditions)
        
#####################################################################################
print("Adding SemFile rows...")        
        
sem_files = ses1.query(SemFile).all()

new_sem_files = [
    SemFile2(
        id = f.id,
        experiment_id=f.sample_id,
        filename=f.filename,
        url=f.url
    )
    for f in sem_files
]
if commit:
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_sem_files)
print("done.")  
      
#####################################################################################

print("Adding RamanFile rows...")        
        
raman_files = ses1.query(RamanFile).all()

new_raman_files = [
    RamanFile2(
        id = f.id,
        experiment_id=f.sample_id,
        filename=f.filename,
        url=f.url,
        wavelength=f.wavelength,
    )
    for f in raman_files
]
if commit:
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_raman_files)
print("done.") 

#####################################################################################

print("Adding RamanSet rows to RamanAnalysis")        

raman_spectrum = ses1.query(RamanSpectrum).all()
raman_set = ses1.query(RamanSet).all()

new_raman_analyses_files = [
    RamanAnalysis2(
        id = f.id,
        raman_file_id=f.raman_file_id,
#         software_name=f.software_name,
#         software_version=f.software_version,
        d_peak_amplitude=f.d_peak_amplitude,
        d_peak_shift=f.d_peak_shift,
        d_fwhm=f.d_fwhm,
        g_peak_amplitude=f.g_peak_amplitude,
        g_peak_shift=f.g_peak_shift,
        g_fwhm=f.g_fwhm,
        g_prime_peak_amplitude=f.g_prime_peak_amplitude,
        g_prime_peak_shift=f.g_prime_peak_shift,
        g_prime_fwhm=f.g_prime_fwhm,        
        d_to_g = [q.d_to_g for q in raman_set if q.sample_id==f.set_id ],
        gp_to_g = [q.gp_to_g for q in raman_set if q.sample_id==f.set_id ]
    )

    for f in raman_spectrum
]
if commit:
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_raman_analyses_files)
print("done.")

Clearing destination database...
done.
Adding furnace rows...
done.
Adding substrate rows...
done.
Adding author rows...
done.
Getting old sample data...
done.
Matching parent tables...
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
name: Graphene
fmap: {1: 1, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2, 10: 2, 11: 2, 12: 2, 13: 2, 14: 2, 15: 2, 16: 2, 17: 2, 18: 2, 19: 2, 20: 2, 21: 2, 22: 2, 23: 2, 24: 2, 25: 2, 26: 2, 27: 2, 28: 2, 29: 2, 30: 2, 31: 2, 32: 2, 33: 2, 34: 2, 35: 2, 36: 2, 37: 2, 38: 2, 39: 2, 40: 2, 41: 2, 42: 2, 43: 2, 44: 2, 45: 2, 46: 2, 47: 2, 48: 2, 49: 2, 50: 2, 51: 2, 52: 2, 53: 2, 54: 2, 55: 2, 56: 2, 57: None, 58: None, 59: None, 60: None, 61: 3, 62: 4, 63: 4, 64: None, 65: 5, 66: 6, 67: 6, 68: 7, 69: 8}
sbmap: {1: 1, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 3, 9: 3, 10: 4, 11: 3, 12: 3, 13: 3, 14: 5, 15: 3, 16: 3, 17: 2, 18: 2, 19: 2, 20: 2, 21: 2, 22: 2, 23: 6, 24: 6, 25: 6, 26: 6, 27: 6, 28: 6, 29: 6, 30: 6, 31: 6, 32: 6, 33: 6, 34: 6, 35: 6, 36: 6, 37: 6, 38: 6, 39: 6, 40: 6, 41: 6, 42: 6, 43: 6, 44: 2, 45: 2, 46: 2, 47: 2, 48: 2, 49: 2, 50: 2, 51: 2, 52: 2, 53: 2, 54: 2, 55: 6, 56: 6, 57: 7, 58: 7, 59: 7, 60: 7, 61: 8, 62: 9, 63: 9, 64: 10, 65: 9, 66: 11, 67: 11, 68: 12, 69: 13}
amap: {1: [<Author(id=1)>], 2: [<Author(id=1)>], 3: [<Author(id=1)>], 4: [<Author(id=1)>], 5: [<Author(id=1)>], 6: [<Author(id=1)>], 7: [<Author(id=1)>], 8: [<Author(id=1)>], 9: [<Author(id=1)>], 10: [<Author(id=1)>], 11: [<Author(id=1)>], 12: [<Author(id=1)>], 13: [<Author(id=1)>], 14: [<Author(id=1)>], 15: [<Author(id=1)>], 16: [<Author(id=1)>], 17: [<Author(id=1)>], 18: [<Author(id=1)>], 19: [<Author(id=1)>], 20: [<Author(id=1)>], 21: [<Author(id=1)>], 22: [<Author(id=1)>], 23: [<Author(id=1)>], 24: [<Author(id=1)>], 25: [<Author(id=1)>], 26: [<Author(id=1)>], 27: [<Author(id=1)>], 28: [<Author(id=1)>], 29: [<Author(id=1)>], 30: [<Author(id=1)>], 31: [<Author(id=1)>], 32: [<Author(id=1)>], 33: [<Author(id=1)>], 34: [<Author(id=1)>], 35: [<Author(id=1)>], 36: [<Author(id=1)>], 37: [<Author(id=1)>], 38: [<Author(id=1)>], 39: [<Author(id=1)>], 40: [<Author(id=1)>], 41: [<Author(id=1)>], 42: [<Author(id=1)>], 43: [<Author(id=1)>], 44: [<Author(id=1)>], 45: [<Author(id=1)>], 46: [<Author(id=1)>], 47: [<Author(id=1)>], 48: [<Author(id=1)>], 49: [<Author(id=1)>], 50: [<Author(id=1)>], 51: [<Author(id=1)>], 52: [<Author(id=1)>], 53: [<Author(id=1)>], 54: [<Author(id=1)>], 55: [<Author(id=1)>], 56: [<Author(id=1)>], 57: [<Author(id=2)>, <Author(id=3)>, <Author(id=4)>, <Author(id=5)>], 58: [<Author(id=2)>, <Author(id=3)>, <Author(id=4)>, <Author(id=5)>], 59: [<Author(id=2)>, <Author(id=3)>, <Author(id=4)>, <Author(id=5)>], 60: [<Author(id=2)>, <Author(id=3)>, <Author(id=4)>, <Author(id=5)>], 61: [<Author(id=6)>, <Author(id=7)>, <Author(id=8)>, <Author(id=9)>, <Author(id=10)>, <Author(id=11)>, <Author(id=12)>, <Author(id=13)>, <Author(id=14)>, <Author(id=15)>, <Author(id=16)>], 62: [<Author(id=17)>, <Author(id=18)>, <Author(id=19)>, <Author(id=20)>, <Author(id=21)>], 63: [<Author(id=17)>, <Author(id=18)>, <Author(id=19)>, <Author(id=20)>, <Author(id=21)>], 64: [<Author(id=22)>, <Author(id=23)>, <Author(id=24)>, <Author(id=25)>, <Author(id=26)>, <Author(id=27)>, <Author(id=28)>, <Author(id=29)>, <Author(id=30)>, <Author(id=31)>, <Author(id=32)>, <Author(id=33)>], 65: [<Author(id=34)>, <Author(id=35)>, <Author(id=36)>, <Author(id=37)>, <Author(id=38)>, <Author(id=39)>, <Author(id=40)>, <Author(id=41)>, <Author(id=42)>, <Author(id=43)>, <Author(id=44)>], 66: [<Author(id=45)>, <Author(id=46)>, <Author(id=47)>, <Author(id=48)>, <Author(id=49)>, <Author(id=50)>, <Author(id=51)>, <Author(id=52)>, <Author(id=53)>], 67: [<Author(id=45)>, <Author(id=46)>, <Author(id=47)>, <Author(id=48)>, <Author(id=49)>, <Author(id=50)>, <Author(id=51)>, <Author(id=52)>, <Author(id=53)>], 68: [<Author(id=54)>, <Author(id=55)>, <Author(id=56)>, <Author(id=57)>, <Author(id=58)>, <Author(id=59)>, <Author(id=60)>, <Author(id=61)>, <Author(id=62)>, <Author(id=63)>, <Author(id=64)>, <Author(id=65)>, <Author(id=66)>], 69: [<Author(id=67)>]}
Done.
Adding Experiment rows...
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
done.
Adding Environment Conditions rows...
None
1
None
2
None
3
None
4
None
5
None
6
None
7
None
8
None
9
None
10
None
11
None
12
None
13
None
14
None
15
None
16
None
17
None
18
None
19
None
20
None
21
None
22
None
23
None
24
None
25
None
26
None
27
None
28
None
29
None
30
None
31
None
32
None
33
None
34
None
35
None
36
None
37
None
38
None
39
None
40
None
41
None
42
None
43
None
44
None
45
None
46
None
47
None
48
None
49
None
50
None
51
None
52
None
53
None
54
None
55
None
56
None
57
None
58
None
59
None
60
None
61
None
62
None
63
None
64
None
65
None
66
None
67
None
68
None
69
[<EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>, <EnvironmentConditions(id=None)>]

Adding SemFile rows...
done.
Adding RamanFile rows...
done.
Adding RamanSet rows to RamanAnalysis
done.