In [1]:
import os

from sqlalchemy import and_, or_
import pandas as pd
pd.set_option("display.max_rows", None)

from grdb.config import Config
from grdb.database.v1_1_0 import dal as db1     # prod dal
from grdb.database import dal as db2            # test dal
from grdb.database.v1_1_0 import Base as Base1  # prod base
from grdb.database import Base as Base2         # test base

from grdb.database.v1_1_0.models import Sample,Recipe,Author

In [2]:
# Setup old schema (production db) as db1 using read only
config_prefix = "PROD_DATABASE"
config_suffix = "_READ"
conf = Config(prefix=config_prefix, suffix=config_suffix, debug=True, try_secrets=False)
db1.init_db(conf, privileges={"read": True, "write": False, "validate": False})
# Testing Configuration and dal initialization
config_prefix = "TEST_DATABASE"
config_suffix = "_ADMIN" 
conf = Config(prefix=config_prefix, suffix=config_suffix, debug=True, try_secrets=False)
db2.init_db(conf, privileges={"read": True, "write": True, "validate": True})

# 0) Stand up fresh empty db2
ses2 = db2.Session()
ses2.close()
Base2.metadata.drop_all(bind=db2.engine)
Base2.metadata.create_all(bind=db2.engine)

In [3]:
# Get all of the samples with their recipe data
ses1 = db1.Session()
pd.read_sql(
    ses1.query(Sample,Recipe).filter(Sample.id==Recipe.sample_id)
    .statement,
    ses1.bind,
)
# For each row:
# 1) Create Expirment row, use ll 1:1 mapped columns
# 1) Get author info from sample.recipe
# 2) create author row (if not exists)
# 3) Add author id to

,id,software_name,software_version,primary_sem_file_id,nanohub_userid,experiment_date,material_name,validated,id_1,sample_id,thickness,diameter,length,catalyst,tube_diameter,cross_sectional_area,tube_length,base_pressure,dewpoint,sample_surface_area
0,1,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,1,1,0.2,NaN,NaN,Palladium,55.0,2376.000,760.0,0.015500,None,50.0
1,2,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,2,2,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015400,None,1500.0
2,3,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,3,3,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015400,None,1500.0
3,4,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,4,4,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015400,None,1500.0
4,5,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,5,5,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015400,None,1500.0
5,6,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,6,6,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015400,None,1500.0
6,7,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,7,7,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015400,None,1500.0
7,8,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,8,8,0.3,NaN,NaN,Nickel,50.8,2026.800,762.0,0.015000,None,75.0
8,9,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,9,9,0.3,NaN,NaN,Nickel,50.8,2026.800,762.0,0.015000,None,75.0
9,10,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,10,10,0.3,NaN,NaN,Nickel,50.8,2026.800,762.0,0.015000,None,22.5
10,11,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,11,11,0.3,NaN,NaN,Nickel,50.8,2026.800,762.0,0.015000,None,75.0
11,12,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,12,12,0.3,NaN,NaN,Nickel,50.8,2026.800,762.0,0.015000,None,75.0
12,13,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,13,13,0.3,NaN,NaN,Nickel,50.8,2026.800,762.0,0.015000,None,75.0
13,14,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,14,14,NaN,NaN,NaN,Nickel,50.8,2026.800,762.0,0.015000,None,NaN
14,15,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,15,15,0.3,NaN,NaN,Nickel,50.8,2026.800,762.0,0.015000,None,75.0
15,16,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,16,16,0.3,NaN,NaN,Nickel,50.8,2026.800,762.0,0.015000,None,75.0
16,17,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,17,17,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.016000,None,1500.0
17,18,gresq,1.0.0-dev1,None,NaN,None,Graphene,True,18,18,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.016000,None,1500.0
18,19,gresq,1.0.0-dev1,None,NaN,2017-09-26,Graphene,True,19,19,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015200,None,1500.0
19,20,gresq,1.0.0-dev1,None,NaN,2017-09-28,Graphene,True,20,20,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015300,None,1500.0
20,21,gresq,1.0.0-dev1,None,NaN,2017-10-10,Graphene,True,21,21,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015500,None,1500.0
21,22,gresq,1.0.0-dev1,None,NaN,2017-10-10,Graphene,True,22,22,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015300,None,1500.0
22,23,gresq,1.0.0-dev1,None,NaN,2018-03-14,Graphene,True,23,23,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.017800,None,1500.0
23,24,gresq,1.0.0-dev1,None,NaN,2018-03-14,Graphene,True,24,24,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.017800,None,1500.0
24,25,gresq,1.0.0-dev1,None,NaN,2018-03-14,Graphene,True,25,25,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.017800,None,1500.0
25,26,gresq,1.0.0-dev1,None,NaN,2018-03-14,Graphene,True,26,26,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.017800,None,1500.0
26,27,gresq,1.0.0-dev1,None,NaN,2018-03-21,Graphene,True,27,27,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.018200,None,1500.0
27,28,gresq,1.0.0-dev1,None,NaN,2018-04-12,Graphene,True,28,28,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.018200,None,1500.0
28,29,gresq,1.0.0-dev1,None,NaN,2018-04-13,Graphene,True,29,29,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019000,None,1500.0
29,30,gresq,1.0.0-dev1,None,NaN,2018-04-14,Graphene,True,30,30,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019000,None,1500.0
30,31,gresq,1.0.0-dev1,None,NaN,2018-04-15,Graphene,True,31,31,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019400,None,1500.0
31,32,gresq,1.0.0-dev1,None,NaN,2018-04-16,Graphene,True,32,32,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019200,None,1500.0
32,33,gresq,1.0.0-dev1,None,NaN,2018-04-16,Graphene,True,33,33,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019200,None,1500.0
33,34,gresq,1.0.0-dev1,None,NaN,2018-04-16,Graphene,True,34,34,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019200,None,1500.0
34,35,gresq,1.0.0-dev1,None,NaN,2018-04-17,Graphene,True,35,35,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019100,None,1500.0
35,36,gresq,1.0.0-dev1,None,NaN,2018-04-17,Graphene,True,36,36,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,NaN,None,1500.0
36,37,gresq,1.0.0-dev1,None,NaN,2018-04-17,Graphene,True,37,37,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,NaN,None,1500.0
37,38,gresq,1.0.0-dev1,None,NaN,2018-04-20,Graphene,True,38,38,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,NaN,None,1500.0
38,39,gresq,1.0.0-dev1,None,NaN,2018-04-20,Graphene,True,39,39,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019100,None,1500.0
39,40,gresq,1.0.0-dev1,None,NaN,2018-04-20,Graphene,True,40,40,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,NaN,None,1500.0
40,41,gresq,1.0.0-dev1,None,NaN,2018-04-22,Graphene,True,41,41,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,NaN,None,1500.0
41,42,gresq,1.0.0-dev1,None,NaN,2018-04-23,Graphene,True,42,42,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019100,None,1500.0
42,43,gresq,1.0.0-dev1,None,NaN,2018-04-23,Graphene,True,43,43,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019100,None,1500.0
43,44,gresq,1.0.0-dev1,None,NaN,2017-08-21,Graphene,True,44,44,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.016200,None,1500.0
44,45,gresq,1.0.0-dev1,None,NaN,2017-09-03,Graphene,True,45,45,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.016000,None,1500.0
45,46,gresq,1.0.0-dev1,None,NaN,2017-09-03,Graphene,True,46,46,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015600,None,1500.0
46,47,gresq,1.0.0-dev1,None,NaN,2017-09-04,Graphene,True,47,47,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015100,None,1500.0
47,48,gresq,1.0.0-dev1,None,NaN,2017-09-28,Graphene,True,48,48,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015400,None,1500.0
48,49,gresq,1.0.0-dev1,None,NaN,2017-09-28,Graphene,True,49,49,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015700,None,1500.0
49,50,gresq,1.0.0-dev1,None,NaN,2017-10-09,Graphene,True,50,50,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.014700,None,1500.0
50,51,gresq,1.0.0-dev1,None,NaN,2018-01-09,Graphene,True,51,51,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.015000,None,1500.0
51,52,gresq,1.0.0-dev1,None,NaN,2018-01-09,Graphene,True,52,52,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.014700,None,1500.0
52,53,gresq,1.0.0-dev1,None,NaN,2018-01-12,Graphene,True,53,53,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.014900,None,1500.0
53,54,gresq,1.0.0-dev1,None,NaN,2018-01-12,Graphene,True,54,54,0.2,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.014500,None,1500.0
54,55,gresq,1.0.0-dev1,None,NaN,2018-04-15,Graphene,True,55,55,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019200,None,1500.0
55,56,gresq,1.0.0-dev1,None,NaN,2018-05-30,Graphene,True,56,56,1.0,NaN,NaN,Palladium Thin Film,50.8,2026.800,762.0,0.019100,None,1500.0
56,57,gresq,0.0.0,None,265127.0,2012-07-12,Graphene,True,57,57,NaN,127.0,1000.0,Palladium,NaN,NaN,NaN,760.000000,None,NaN
57,58,gresq,0.0.0,None,265127.0,2012-07-12,Graphene,True,58,58,NaN,127.0,1000.0,Palladium,NaN,NaN,NaN,760.000000,None,NaN
58,59,gresq,0.0.0,None,265127.0,2012-07-12,Graphene,True,59,59,NaN,127.0,1000.0,Palladium,NaN,NaN,NaN,760.000000,None,NaN
59,60,gresq,0.0.0,None,265127.0,2012-07-12,Graphene,True,60,60,NaN,127.0,1000.0,Palladium,NaN,NaN,NaN,760.000000,None,NaN
60,61,gresq,0.0.0,None,265127.0,2014-06-10,Graphene,True,61,61,25.0,NaN,NaN,Palladium,25.4,507.000,NaN,0.007501,None,NaN
61,62,gresq,0.0.0,None,265127.0,2014-06-10,Graphene,True,62,62,25.0,NaN,NaN,Platinum,40.0,1257.000,NaN,760.000000,None,NaN
62,63,gresq,0.0.0,None,265127.0,2014-06-10,Graphene,True,63,63,25.0,NaN,NaN,Platinum,40.0,1257.000,NaN,760.000000,None,NaN
63,64,gresq,0.0.0,None,265127.0,2012-02-28,Graphene,True,64,64,200.0,NaN,NaN,Platinum,NaN,NaN,NaN,760.000000,None,NaN
64,65,gresq,0.0.0,None,265127.0,2015-07-15,Graphene,True,65,65,25.0,NaN,NaN,Platinum,28.0,616.000,NaN,760.000000,None,NaN
65,66,gresq,0.0.0,None,265127.0,2014-11-11,Graphene,True,66,66,350.0,NaN,NaN,Copper,102.0,8107.000,NaN,0.080000,None,NaN
66,67,gresq,0.0.0,None,265127.0,2014-11-11,Graphene,True,67,67,350.0,NaN,NaN,Copper,102.0,8107.000,NaN,0.080000,None,NaN
67,68,gresq,0.0.0,None,265127.0,2009-06-05,Graphene,True,68,68,25.0,NaN,NaN,Copper,22.0,380.000,NaN,0.500000,None,NaN
68,80,gresq,1.1.0-dev0,None,NaN,2019-12-11,Graphene,True,80,80,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
69,81,gresq,1.1.0-dev0,None,NaN,2019-12-11,Graphene,True,81,81,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
70,82,gresq,1.1.0-dev0,None,NaN,2019-12-16,Graphene,True,82,82,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
71,83,gresq,1.1.0-dev0,None,NaN,2019-12-16,Graphene,True,83,83,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
72,84,gresq,1.1.0-dev0,None,NaN,2019-12-16,Graphene,True,84,84,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
73,85,gresq,1.1.0-dev0,None,NaN,2019-12-16,Graphene,True,85,85,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
74,86,gresq,1.1.0-dev0,None,NaN,2019-12-17,Graphene,True,86,86,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
75,87,gresq,1.1.0-dev0,None,NaN,2019-12-18,Graphene,True,87,87,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
76,88,gresq,1.1.0-dev0,None,NaN,2019-12-18,Graphene,True,88,88,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
77,89,gresq,1.1.0-dev0,None,NaN,2019-12-18,Graphene,True,89,89,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
78,90,gresq,1.1.0-dev0,None,NaN,2020-01-31,Graphene,True,90,90,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
79,91,gresq,1.1.0-dev0,None,NaN,2020-02-01,Graphene,True,91,91,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
80,92,gresq,1.1.0-dev0,None,NaN,2020-02-02,Graphene,True,92,92,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
81,93,gresq,1.1.0-dev0,None,NaN,2020-02-07,Graphene,True,93,93,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
82,94,gresq,1.1.0-dev0,None,NaN,2020-02-07,Graphene,True,94,94,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
83,95,gresq,1.1.0-dev0,None,NaN,2020-09-21,Graphene,True,95,95,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
84,96,gresq,1.1.0-dev0,None,NaN,2020-09-21,Graphene,True,96,96,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
85,97,gresq,1.1.0-dev0,None,NaN,2020-09-22,Graphene,True,97,97,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
86,98,gresq,1.1.0-dev0,None,NaN,2020-09-22,Graphene,True,98,98,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
87,99,gresq,1.1.0-dev0,None,NaN,2020-09-22,Graphene,True,99,99,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
88,100,gresq,1.1.0-dev0,None,NaN,2020-09-22,Graphene,True,100,100,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
89,101,gresq,1.1.0-dev0,None,NaN,2020-09-23,Graphene,True,101,101,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
90,102,gresq,1.1.0-dev0,None,NaN,2020-09-24,Graphene,True,102,102,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
91,103,gresq,1.1.0-dev0,None,NaN,2020-09-24,Graphene,True,103,103,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
92,104,gresq,1.1.0-dev0,None,NaN,2020-09-24,Graphene,True,104,104,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
93,105,gresq,1.1.0-dev0,None,NaN,2020-09-24,Graphene,True,105,105,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
94,106,gresq,1.1.0-dev0,None,NaN,2020-09-25,Graphene,True,106,106,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
95,107,gresq,1.1.0-dev0,None,NaN,2020-09-26,Graphene,True,107,107,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
96,108,gresq,1.1.0-dev0,None,NaN,2020-09-26,Graphene,True,108,108,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
97,109,gresq,1.1.0-dev0,None,NaN,2020-09-26,Graphene,True,109,109,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
98,110,gresq,1.1.0-dev0,None,NaN,2020-09-27,Graphene,True,110,110,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
99,111,gresq,1.1.0-dev0,None,NaN,2020-09-27,Graphene,True,111,111,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
100,112,gresq,1.1.0-dev0,None,NaN,2020-09-27,Graphene,True,112,112,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
101,113,gresq,1.1.0-dev0,None,NaN,2020-09-27,Graphene,True,113,113,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
102,114,gresq,1.1.0-dev0,None,NaN,2020-09-28,Graphene,True,114,114,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
103,115,gresq,1.1.0-dev0,None,NaN,2020-09-28,Graphene,True,115,115,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
104,116,gresq,1.1.0-dev0,None,NaN,2020-10-01,Graphene,True,116,116,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
105,117,gresq,1.1.0-dev0,None,NaN,2020-10-02,Graphene,True,117,117,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
106,118,gresq,1.1.0-dev0,None,NaN,2020-10-04,Graphene,True,118,118,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
107,119,gresq,1.1.0-dev0,None,NaN,2020-10-06,Graphene,True,119,119,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
108,120,gresq,1.1.0-dev0,None,NaN,2020-10-08,Graphene,True,120,120,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
109,121,gresq,1.1.0-dev0,None,NaN,2020-10-09,Graphene,True,121,121,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
110,122,gresq,1.1.0-dev0,None,NaN,2020-10-11,Graphene,True,122,122,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
111,123,gresq,1.1.0-dev0,None,NaN,2020-10-11,Graphene,True,123,123,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
112,124,gresq,1.1.0-dev0,None,NaN,2020-10-12,Graphene,True,124,124,25.0,NaN,NaN,Copper,25.4,506.707,1000.0,0.760000,None,150.0
113,125,gresq,0.0.0,None,210937.0,2021-01-20,Graphene,False,126,125,NaN,NaN,NaN,Palladium,25.0,NaN,500.0,760.000000,None,150.0

In [4]:
ses1 = db1.Session()
unique_substrate_query = ses1.query(Recipe.catalyst, Recipe.thickness, Recipe.diameter, Recipe.length, Recipe.sample_surface_area).distinct().filter(
        or_(
            Recipe.catalyst != None,
            Recipe.thickness != None,
            Recipe.diameter != None,
            Recipe.sample_surface_area != None,
            Recipe.length != None,
        )
    )

pd.read_sql(
    unique_substrate_query.statement,
    ses1.bind,
)

               catalyst  thickness  diameter  length  sample_surface_area
0             Palladium        0.2       NaN     NaN                 50.0
1   Palladium Thin Film        0.2       NaN     NaN               1500.0
2                Nickel        0.3       NaN     NaN                 75.0
3                Nickel        0.3       NaN     NaN                 22.5
4                Nickel        NaN       NaN     NaN                  NaN
5   Palladium Thin Film        1.0       NaN     NaN               1500.0
6             Palladium        NaN     127.0  1000.0                  NaN
7             Palladium       25.0       NaN     NaN                  NaN
8              Platinum       25.0       NaN     NaN                  NaN
9              Platinum      200.0       NaN     NaN                  NaN
10               Copper      350.0       NaN     NaN                  NaN
11               Copper       25.0       NaN     NaN                  NaN
12               Copper       25.0       NaN     NaN                150.0
13            Palladium        NaN       NaN     NaN                150.0

In [4]:
# Test query for furnace data

ses1 = db1.Session()
unique_furnace_query = ses1.query(Recipe.tube_diameter, Recipe.cross_sectional_area, Recipe.tube_length).distinct().filter(
        or_(
            Recipe.tube_diameter != None,
            Recipe.cross_sectional_area != None,
            Recipe.tube_length != None,
        )
    )
pd.read_sql(
    unique_furnace_query.statement,
    ses1.bind,
)

   tube_diameter  cross_sectional_area  tube_length
0           55.0              2376.000        760.0
1           50.8              2026.800        762.0
2           25.4               507.000          NaN
3           40.0              1257.000          NaN
4           28.0               616.000          NaN
5          102.0              8107.000          NaN
6           22.0               380.000          NaN
7           25.4               506.707       1000.0
8           25.0                   NaN        500.0

In [5]:
# Read all unique authors from old schema
from grdb.database.v1_1_0.v1_1_0.models import Author

ses1 = db1.Session()
#unique_authors_query = ses1.query(
#        Author.sample_id,Author.first_name, Author.last_name, Author.institution
#    ).filter(Author.sample_id==Sample.id).group_by(Author.sample_id,Author.first_name, Author.last_name)
unique_authors_query = ses1.query(
        Author.first_name, Author.last_name, Author.institution
    ).distinct()
pd.read_sql(
    unique_authors_query.statement,
    ses1.bind,
)

    first_name         last_name                                 institution
0       Kaihao             Zhang  University of Illinois at Urbana-Champaign
1     Xiaohong                An                     Northeastern University
2       Fangze               Liu                     Northeastern University
3    Yung Joon              Jung                     Northeastern University
4      Swastik               Kar                     Northeastern University
5       Doglin                Ma                           Peking University
6       Mengxi               Liu                           Peking University
7         Teng               Gao                           Peking University
8         Cong                Li                           Peking University
9       Jingyu               Sun                           Peking University
10      Yufeng               Nie                           Peking University
11    Qingqing                Ji                           Peking University
12          Yu             Zhang                           Peking University
13       Xiuju              Song                           Peking University
14     Yanfeng             Zhang                           Peking University
15    Zhongfan               Liu                           Peking University
16          Ke              Xiao                         Tsinghua University
17    Huaqiang                Wu                         Tsinghua University
18    Hongming                Lv                         Tsinghua University
19    Xiaoming                Wu                         Tsinghua University
20          He              Qian                         Tsinghua University
21        Libo               Gao                 Chinese Academy of Sciences
22      Wencai               Ren                 Chinese Academy of Sciences
23     Huilong                Xu                           Peking University
24          Li               Jin                 Chinese Academy of Sciences
25    Zhenxing              Wang                           Peking University
26        Teng                Ma                 Chinese Academy of Sciences
27    Lai-Peng                Ma                 Chinese Academy of Sciences
28     Zhiyong             Zhang                           Peking University
29       Qiang                Fu                 Chinese Academy of Sciences
30    Lian-Mao              Peng                           Peking University
31       Xinhe               Bao                 Chinese Academy of Sciences
32    Hui-Ming             Cheng                 Chinese Academy of Sciences
33     Vitaliy           Babenko                        University of Oxford
34      Adrian           Murdock                        University of Oxford
35       Antal              Koos                        University of Oxford
36        Jude           Britton                        University of Oxford
37      Alison          Crossley                        University of Oxford
38      Philip           Holdway                        University of Oxford
39    Jonathan            Moffat          Oxford Instruments Asylum Research
40        Jian             Huang                        University of Oxford
41        Jack  Alexander-Webber                        University of Oxford
42       Robin          Nicholas                        University of Oxford
43      Nicole           Grobert                        University of Oxford
44    Dong Soo              Choi                     Sungkyunkwan University
45    Keun Soo               Kim                           Sejong University
46  Hyeongkeun               Kim      Korea Electronics Technology Institute
47        Yena               Kim                     Sungkyunkwan University
48    TaeYoung               Kim                           Gachon University
49     Se-hyun               Rhy      Korea Electronics Technology Institute
50   Cheol-Min              Yang   Korea Institute of Science and Technology
51      Dae Ho              Yoon                     Sungkyunkwan University
52    Woo Seok              Yang      Korea Electronics Technology Institute
53     Xuesong                Li               University of Texas at Austin
54      Weiwei               Cai               University of Texas at Austin
55       Jinho                An               University of Texas at Austin
56     Seyoung               Kim               University of Texas at Austin
57     Junghyo               Nah               University of Texas at Austin
58    Dongxing              Yang               University of Texas at Austin
59     Richard             Piner               University of Texas at Austin
60       Aruna       Velamakanni               University of Texas at Austin
61       Inhwa              Jung               University of Texas at Austin
62     Emanuel             Tutuc               University of Texas at Austin
63      Sanjay          Banerjee               University of Texas at Austin
64       Luigi           Colombo                           Texas Instruments
65      Rodney             Ruoff               University of Texas at Austin
66       Aagam              Shah  University of Illinois at Urbana-Champaign
67     Mitisha            Surana  University of Illinois at Urbana-Champaign
68         Jad           Yaacoub  University of Illinois at Urbana-Champaign

In [5]:
ses1 = db1.Session
authors = ses1.query(
    Author.sample_id, Author.first_name, Author.last_name, Author.institution
).group_by(Author.first_name, Author.last_name)
ses1.query(Sample.id,Sample.nanohub_userid).filter(Sample.id.in_(authors))

In [6]:
ses1 = db1.Session()
# authors = ses1.query(Author.first_name, Author.last_name, Author.institution).distinct()
# TODO: SAMPLE TABLE IS COMPLETELY EMPTY
samples = ses1.query(Sample,Recipe).filter(Sample.id==Recipe.sample_id)
for s in samples:
    print(f"name: {s.Sample.material_name}")
    print(f"{s.Recipe.base_pressure,s.Recipe.catalyst,s.Recipe.thickness,s.Recipe.diameter,s.Recipe.length,s.Recipe.sample_surface_area}")

name: Graphene
(0.0155, 'Palladium', 0.2, None, None, 50.0)
name: Graphene
(0.0154, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 22.5)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', None, None, None, None)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.015, 'Nickel', 0.3, None, None, 75.0)
name: Graphene
(0.016, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.016, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0152, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0153, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0155, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0153, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0178, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0178, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0178, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0178, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0182, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0182, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.019, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.019, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0194, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0192, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0192, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0192, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(None, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0162, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.016, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0156, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0151, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0154, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0157, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0147, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.015, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0147, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0149, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0145, 'Palladium Thin Film', 0.2, None, None, 1500.0)
name: Graphene
(0.0192, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(0.0191, 'Palladium Thin Film', 1.0, None, None, 1500.0)
name: Graphene
(760.0, 'Palladium', None, 127.0, 1000.0, None)
name: Graphene
(760.0, 'Palladium', None, 127.0, 1000.0, None)
name: Graphene
(760.0, 'Palladium', None, 127.0, 1000.0, None)
name: Graphene
(760.0, 'Palladium', None, 127.0, 1000.0, None)
name: Graphene
(0.007501, 'Palladium', 25.0, None, None, None)
name: Graphene
(760.0, 'Platinum', 25.0, None, None, None)
name: Graphene
(760.0, 'Platinum', 25.0, None, None, None)
name: Graphene
(760.0, 'Platinum', 200.0, None, None, None)
name: Graphene
(760.0, 'Platinum', 25.0, None, None, None)
name: Graphene
(0.08, 'Copper', 350.0, None, None, None)
name: Graphene
(0.08, 'Copper', 350.0, None, None, None)
name: Graphene
(0.5, 'Copper', 25.0, None, None, None)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(0.76, 'Copper', 25.0, None, None, 150.0)
name: Graphene
(760.0, 'Palladium', None, None, None, 150.0)

In [8]:
######################################################################################
# Migration script
# ToDo:
# - TESTING!!!
# - nanohub_userid
# - environment_conditions
# - sem_files + analysis
# - raman_files + analysis
# - software versions
######################################################################################

from grdb.database.v1_1_0.models import Author
from grdb.database.models import Author as Author2
from grdb.database.models import Furnace as Furnace2
from grdb.database.models import Experiment as Experiment2
from grdb.database.models import Recipe as Recipe2
from grdb.database.models import PreparationStep as PreparationStep2
from grdb.database.models import Substrate as Substrate2
from grdb.database.models import EnvironmentConditions as EnvironmentConditions2


commit = True
limit = 200

from math import isclose

# 0) Stand up fresh empty db2
print("Clearing destination database...")
ses2 = db2.Session()
ses2.close()
Base2.metadata.drop_all(bind=db2.engine)
Base2.metadata.create_all(bind=db2.engine)
print("done.")




print("Adding furnace rows...")
furnaces = unique_furnace_query
new_furnaces = [
    Furnace2(
        tube_diameter =  f.tube_diameter,
        cross_sectional_area = f.cross_sectional_area,
        tube_length = f.tube_length
    ) for f in furnaces
]
if commit:
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_furnaces)
print("done.")
       

print("Adding substrate rows...")
substrates = unique_substrate_query
new_substrates = [
    Substrate2(
        catalyst = s.catalyst,
        thickness = s.thickness,
        diameter = s.diameter,
        surface_area = s.sample_surface_area,
        length = s.length
    ) for s in substrates
]
if commit:
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_substrates)
print("done.")

print("Adding author rows...")
authors = unique_authors_query
new_authors = [
    Author2(
        first_name = a.first_name,
        last_name = a.last_name,
        institution = a.institution
    ) for a in authors
]

# Submit type of call/ insert/update
if commit:
    # call factory function gives live session from class 
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_authors)
print("done.")

print("Getting old sample data...")
ses1 = db1.Session()
samples = ses1.query(Sample,Recipe).filter(Sample.id==Recipe.sample_id).limit(limit)
oauthors = ses1.query(Author).all()
print("done.")

#####################################################################################
# At this point unique rows for furnace, substrate and Authors have been created
# Now, Loop back through the samples and match rows in furnace, substrate and authors
# Build a map from Experiment id  -> furnace_id, etc. for each sample/experiment id
# Note this assumes that the experiment id will map to the (old) sample id.
######################################################################################
ses3 = db2.Session()
new_furnaces = ses3.query(Furnace2).all()
new_substrates = ses3.query(Substrate2).all()
new_authors = ses3.query(Author2).all()
    
furnacemap = {}
substratemap = {}
authormap = {}
tol = 0.01
print ("Matching parent tables...")
for s in samples:
    authormap[s.Sample.id]=[]
    print(f"name: {s.Sample.material_name}")
    #print(f"{s.Recipe.base_pressure,s.Recipe.catalyst}")
    
    #################################################################################
    # Match to a row in the furnace table
    #################################################################################
    for f in new_furnaces:
        #print(f"id: {f.id}")
        match = match1 = match2 = match3 = False
        null = null1 = null2 = null3 = False
        if f.tube_diameter:
            if s.Sample.recipe.tube_diameter:
                if isclose(f.tube_diameter,s.Sample.recipe.tube_diameter,rel_tol=0.001,abs_tol=0.001):
                    match1 = True
        else:
            if not s.Sample.recipe.tube_diameter:
                match1 = True
                null1 = True
        if f.tube_length:
            if s.Sample.recipe.tube_length:
                if isclose(f.tube_length,s.Sample.recipe.tube_length,rel_tol=0.001,abs_tol=0.001):
                    match2 = True
        else:
            if not s.Sample.recipe.tube_length:
                match2 = True
                null2 = True
        if f.cross_sectional_area:
            if s.Sample.recipe.cross_sectional_area:
                if isclose(f.cross_sectional_area,s.Sample.recipe.cross_sectional_area,rel_tol=0.001,abs_tol=0.001):
                    match3 = True
        else:
            if not s.Sample.recipe.cross_sectional_area:
                match3 = True
                null3 = True
        # If there are any non null matches    
        match = match1 and match2 and match3
        if match:
            furnacemap[s.Sample.id] = f.id
            #print(f"match: {s.Sample.id}: {f.id}")
            break
        else:
            furnacemap[s.Sample.id] = None
            
        
    #################################################################################
    # Match to row in Substrate table
    #################################################################################
    for sb in new_substrates:
        match = match1 = match2 = match3 = match4 = match5 = False
        if sb.catalyst:
            if sb.catalyst == s.Sample.recipe.catalyst:
                match1 = True
        else:
            if not s.Sample.recipe.catalyst:
                match1 = True
        if sb.thickness:
            if s.Sample.recipe.thickness:
                if isclose(sb.thickness,s.Sample.recipe.thickness,rel_tol=tol,abs_tol=tol):
                    match2 = True
        else:
            if not s.Sample.recipe.thickness:
                match2 = True
        if sb.diameter:
            if s.Sample.recipe.diameter:
                if isclose(sb.diameter,s.Sample.recipe.diameter,rel_tol=tol,abs_tol=tol):
                    match3 = True
        else:
            if not s.Sample.recipe.diameter:
                match3 = True
        if sb.length:
            if s.Sample.recipe.length:
                if isclose(sb.length,s.Sample.recipe.length,rel_tol=tol,abs_tol=tol):
                    match4 = True
        else:
            if not s.Sample.recipe.length:
                match4 = True
        if sb.surface_area:
            if s.Sample.recipe.sample_surface_area:
                if isclose(sb.surface_area,s.Sample.recipe.sample_surface_area,rel_tol=tol,abs_tol=tol):
                    match5 = True
        else:
            if not s.Sample.recipe.sample_surface_area:
                match5 = True
        match = match1 and match2 and match3 and match4 and match5
        if match:
            substratemap[s.Sample.id] = sb.id
            break
        else:
            substratemap[s.Sample.id] = None
    #################################################################################
    # Match to row(s) in Author table
    #################################################################################
    for oa in oauthors:
        if not oa.sample_id == s.Sample.id:
            continue
        for na in new_authors:
            match = match1 = match2 = False
            if oa.first_name == na.first_name:
                match1 = True
            if oa.last_name == na.last_name:
                match2 = True
            match = match1 and match2
            if match:
                authormap[s.Sample.id].append(na)
                break
        
        
    

#Print out the maps
print (f"fmap: {furnacemap}")
print (f"sbmap: {substratemap}")
print(f"amap: {authormap}")
print ("Done.")        

#####################################################################################
#####################################################################################

print("Adding Experiment rows...")
with db2.session_scope(autocommit=True) as ses2:
    for s in samples:
        print(f"{s.Sample.id}")
        try:
            carbon_source = s.Recipe.carbon_source
        except IndexError:
            carbon_source = None
        

            
        # Add the new experiment based on the old sample
        # Create a recipe for each old sample and add all of its prep steps
        newexp = Experiment2(
                id=s.Sample.id,
                furnace_id = furnacemap[s.Sample.id],
                substrate_id = substratemap[s.Sample.id],
                authors = authormap[s.Sample.id],
                material_name=s.Sample.material_name,
                experiment_date=s.Sample.experiment_date,
                recipe = Recipe2(
                    carbon_source=carbon_source,
                    base_pressure=s.Recipe.base_pressure,
                    preparation_steps = [
                        PreparationStep2(
                            name=step.name,
                            duration=step.duration
                        ) for step in s.Recipe.preparation_steps
                    ]
                    ),
                
                )
        
        ses2.add(newexp)

print("done.")

#####################################################################################
#####################################################################################

print("Adding Environment Conditions rows...")
new_environment_conditions = [
    EnvironmentConditions2(
        # TODO: Where do we get ambient temperature
        dew_point = s.Sample.recipe.dewpoint,
        ambient_temperature = 10
    ) for s in samples
]
for s in samples:
    print(f"{s.Sample.recipe.dewpoint}")
    print(f"{s.Sample.id}")
print(new_environment_conditions)
if commit:
    with db2.session_scope(autocommit=True) as ses2:
        ses2.add_all(new_environment_conditions) 
print("done.")

Clearing destination database...

OperationalError: (pymysql.err.OperationalError) (1091, "Can't DROP 'fk_default_analysis'; check that column/key exists")
[SQL: ALTER TABLE sem_file DROP FOREIGN KEY fk_default_analysis]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

In [38]:
%env

{'USER': 'root',
 'VSCODE_WSL_EXT_LOCATION': '/mnt/c/Users/byoon/.vscode/extensions/ms-vscode-remote.remote-wsl-0.56.2',
 'SHLVL': '0',
 'HOME': '/root',
 'WSL_DISTRO_NAME': 'Ubuntu',
 'LOGNAME': 'root',
 'NAME': 'DESKTOP-G15VBC3',
 '_': '/root/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/node',
 'TERM': 'xterm-color',
 'PATH': '/root/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/bin:/root/.nvm/versions/node/v14.16.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/:/mnt/c/Program Files/MySQL/MySQL Shell 8.0/bin/:/mnt/c/Users/byoon/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/byoon/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin',
 'VSCODE_AGENT_FOLDER': '/root/.vscode-server',
 'LANG': 'C.UTF-8',
 'SHELL': '/bin/bash',
 'PWD': '/mnt/c/Users/byoon/AppData/Local/Programs/Microsoft VS Code',
 'HOSTTYPE': 'x86_64',
 'WSLENV': 'VSCODE_WSL_EXT_LOCATION/up',
 'VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH': '/root/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/remote/node_modules',
 'VSCODE_CWD': '/mnt/c/Users/byoon/AppData/Local/Programs/Microsoft VS Code',
 'NVM_INC': '/root/.nvm/versions/node/v14.16.0/include/node',
 'MOTD_SHOWN': 'update-motd',
 'NVM_DIR': '/root/.nvm',
 'NVM_CD_FLAGS': '',
 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop',
 'NVM_BIN': '/root/.nvm/versions/node/v14.16.0/bin',
 'VSCODE_LOG_NATIVE': 'false',
 'VSCODE_AMD_ENTRYPOINT': 'vs/server/remoteExtensionHostProcess',
 'VSCODE_PIPE_LOGGING': 'true',
 'VSCODE_VERBOSE_LOGGING': 'true',
 'VSCODE_EXTHOST_WILL_SEND_SOCKET': 'true',
 'VSCODE_HANDLES_UNCAUGHT_ERRORS': 'true',
 'VSCODE_LOG_STACK': 'false',
 'VSCODE_NLS_CONFIG': '{"locale":"en","availableLanguages":{}}',
 'VSCODE_IPC_HOOK_CLI': '/tmp/vscode-ipc-5cdbf95f-036d-470f-b3d5-20d55e1f7a39.sock',
 'APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL': 'true',
 'PYTHONPATH': '/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles:/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/lib/python',
 'PYTHONUNBUFFERED': '1',
 'PYTHONIOENCODING': 'utf-8',
 'JPY_PARENT_PID': '795',
 'CLICOLOR': '1',
 'PAGER': 'cat',
 'GIT_PAGER': 'cat',
 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline'}